version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: draw_app_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: drawapp
    ports:
      - "5433:5432"    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - draw_network

volumes:
  postgres_data:

networks:
  draw_network:
